/**:
  ros__parameters:
    # World: obstacle_avoidance_4.world
    # Model: goal_marker_1
    # Full pose (x y z roll pitch yaw): 0.0  -2.45  0.001  0  0  0
    # Robot spawn: x=0.0  y=0.0  yaw=0.0
    waypoints: [0.0, -2.45]
    goal_tolerance: 0.20

a_star_node:
  ros__parameters:
    waypoints: [0.0, -2.45]
    goal_tolerance: 0.15

    bounds: [-3.0, -3.0, 3.0, 3.0]
    resolution: 0.10
    inflation_radius: 0.20
    path_stride: 2

    # Rectangular obstacles:
    # [xmin, ymin, xmax, ymax, xmin, ymin, xmax, ymax, ...]
    obstacles: [
      # Wall_10
      -1.50, 2.55, -0.75, 2.65,

      # Wall_20
      0.75, 2.55, 1.50, 2.65,

      # Wall_30
      -1.50, 0.65, -1.40, 2.55,

      # Wall_40
      1.40, 0.65, 1.50, 2.55,

      # Wall_50
      -1.40, 0.65, 1.40, 0.75,

      # Wall_60
      -1.50, -0.95, 1.50, -0.85
    ]

hybrid_a_star_bug0_node:
  ros__parameters:
    waypoints: [0.0, -2.45]
    goal_tolerance: 0.1

    bounds: [-3.0, -3.0, 3.0, 3.0]
    resolution: 0.10
    inflation_radius: 0.30
    path_stride: 1
    known_obstacle_tolerance: 0.15
    known_obstacle_angle_window_deg: 20.0

    obstacles: [
      -1.50, 2.55, -0.75, 2.65,
      0.75, 2.55, 1.50, 2.65,
      -1.50, 0.65, -1.40, 2.55,
      1.40, 0.65, 1.50, 2.55,
      -1.40, 0.65, 1.40, 0.75,
      -1.50, -0.95, 1.50, -0.85
    ]