-d /home/mateo/Documents/octavo/puzzlebot-pallet-loader/src/fpga_lifter_bridge/verilog/fpga_lifter_logic/impl/gwsynthesis/fpga_lifter_logic.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/mateo/Documents/octavo/puzzlebot-pallet-loader/src/fpga_lifter_bridge/verilog/fpga_lifter_logic/src/forklift_controller_tangnano20k.cst
-cfg /home/mateo/Documents/octavo/puzzlebot-pallet-loader/src/fpga_lifter_bridge/verilog/fpga_lifter_logic/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
