# =============================================================================
# ekf_aruco_params.yaml
# =============================================================================

ekf_aruco_localization_node:
  ros__parameters:

    # Robot
    wheel_radius: 0.05
    wheel_base: 0.18
    dt: 0.05

    # Primero prueba navegación con false.
    # Cuando ya detecte bien los ArUcos, cámbialo a true.
    use_aruco: true

    # Ruido de proceso Q (ahora proporcional al movimiento)
    # Valores más altos porque se multiplican por desplazamiento
    q_x: 0.5
    q_y: 0.5
    q_theta: 0.3

    # Ruido de medición R — qué tanto confiar en las correcciones ArUco
    # Más bajo = más confianza en ArUco
    # Valores mas altos = menos confianza en ArUco y correcciones mas suaves.
    # El bearing se deja mas alto porque pequenas variaciones hacen "bailar" el yaw.
    r_range: 0.50
    r_bearing: 1.00

    mahalanobis_threshold: 9.21

    # Topics
    ekf_odom_topic: "/ekf_odom"
    aruco_topic: "/aruco_measurements"
    use_joint_states: false
    joint_states_topic: "/joint_states"
    left_wheel_joint: "wheel_left_joint"
    right_wheel_joint: "wheel_right_joint"
    left_wheel_sign: 1.0
    right_wheel_sign: 1.0

    # Frames TF
    odom_frame: "odom"
    base_frame: "base_link"
    laser_frame: "laser"

    # Pose inicial del robot
    initial_x: 0.0
    initial_y: 0.0
    initial_yaw: 3.08
    initial_cov_x: 0.01
    initial_cov_y: 0.01
    initial_cov_yaw: 0.10

    # Mapa de landmarks ArUco
    # Mismo frame que config/aruco_landmarks.yaml.
    # marker_theta se mantiene en 0.0 porque el EKF actual solo usa x/y.
    marker_ids:   [0,     1,     2,     3,    4,     5,     6,      7,      8,      9,     10]
    marker_x:     [-1.78, -2.75, -1.78, 1.08, 1.08, -0.41, -0.41,  -1.61, -1.61,  2.06,  2.06]
    marker_y:     [-1.84,  0.28,  1.84, 1.84, -1.84, 0.54, -0.64,  -0.54,  0.64, -1.47,  1.06]
    marker_theta: [0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,    0.0,    0.0,   0.0,   0.0]

# ── ArUco Detector Node ───────────────────────────────────────────────────────
aruco_detector_node:
  ros__parameters:
    camera_topic: "/camera/image_raw/compressed"
    calib_file: "/home/valeria/puzzlebot-pallet-loader/src/camera_dataset/camera_calibration.npz"
    # Tamano efectivo calibrado con cinta: 2.45 m medidos por vision vs 2.71 m reales.
    marker_size: 0.0885
    aruco_dictionary: "DICT_4X4_50"
    allowed_marker_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    camera_x_offset: 0.08
    camera_y_offset: 0.0
    camera_yaw_offset: 0.0

    publish_annotated_image: true
    annotated_image_topic: "/aruco/annotated"
    measurements_topic: "/aruco_measurements"
